### PR TITLE
Commiting Homework

### PR DESCRIPTION
**Pull request by JzfL**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
adding image of HW1
## What did you learn from the changes you have made?
visualizing tables is critical
## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
choose a differe3nt table combination
## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
N/A
## How were these changes tested?
it was a image file
## Checklist
- [X] I can confirm that my changes are working as intended

### CODE REVIEW

**Review by ananyajha2000 — COMMENTED** [review]
Relationship type is missing. It would be one to many as a single booth (identified by booth number in the booth table) can be assigned to multiple vendors over time, each with a different market_date.

**Comment by JzfL** [comment]
PLease find updated HW1 ERD

**Comment by JzfL** [comment]
> Relationship type is missing. It would be one to many as a single booth (identified by booth number in the booth table) can be assigned to multiple vendors over time, each with a different market_date.

Please find updated HW1 ERD

**Review by ananyajha2000 — COMMENTED** [review]
Looks good! 10/10 for all!

**Review by ananyajha2000 — COMMENTED** [review]
Union question missing from HW 4 7/10

**Comment by JzfL** [comment]
> Union question missing from HW 4 7/10

Hi, No, it is not missing, please check homework_5_sql file, it was on the same commit and my commit message. It was mentioned by Thomas there was a miss-match of md and sql file due to his shift-around. Please update my marks accordingly

**Review by ananyajha2000 — COMMENTED** [review]
HW 4 updated- 10/10
HW 5& 6 graded 10/10

**Comment by JzfL** [comment]
Thank you

**Pull request merged**
